export interface Cookie {
  domain: string;
  includeSubdomains: boolean;
  path: string;
  secure: boolean;
  expires: number;
  name: string;
  value: string;
}

export interface BrowserCookieExtractor {
  browser: string;
  extract(domain?: string): Promise<Cookie[]>;
}

function parseBool(val: string): boolean {
  return val.toUpperCase() === "TRUE";
}

export function parseNetscapeCookieFile(content: string): Cookie[] {
  const cookies: Cookie[] = [];
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const parts = line.split("\t");
    if (parts.length < 7) continue;
    const [domain, includeSubdomains, path, secure, expires, name, value] =
      parts;
    cookies.push({
      domain,
      includeSubdomains: parseBool(includeSubdomains),
      path,
      secure: parseBool(secure),
      expires: parseInt(expires, 10),
      name,
      value: value ?? "",
    });
  }
  return cookies;
}

export function serializeNetscapeCookieFile(cookies: Cookie[]): string {
  const header = "# Netscape HTTP Cookie File\n# Generated by dlpx\n";
  const lines = cookies.map((c) =>
    [
      c.domain,
      c.includeSubdomains ? "TRUE" : "FALSE",
      c.path,
      c.secure ? "TRUE" : "FALSE",
      c.expires,
      c.name,
      c.value,
    ].join("\t"),
  );
  return header + lines.join("\n") + "\n";
}

function domainMatches(cookieDomain: string, requestHost: string): boolean {
  const cd = cookieDomain.startsWith(".") ? cookieDomain.slice(1) : cookieDomain;
  return requestHost === cd || requestHost.endsWith(`.${cd}`);
}

export class CookieJar {
  private cookies: Cookie[] = [];

  load(content: string): void {
    const parsed = parseNetscapeCookieFile(content);
    for (const c of parsed) {
      this.set(c);
    }
  }

  set(cookie: Cookie): void {
    const idx = this.cookies.findIndex(
      (c) =>
        c.domain === cookie.domain &&
        c.path === cookie.path &&
        c.name === cookie.name,
    );
    if (idx >= 0) {
      this.cookies[idx] = cookie;
    } else {
      this.cookies.push(cookie);
    }
  }

  get(domain: string, path: string, name: string): Cookie | undefined {
    const now = Math.floor(Date.now() / 1000);
    return this.cookies.find(
      (c) =>
        c.name === name &&
        c.path === path &&
        domainMatches(c.domain, domain) &&
        (c.expires === 0 || c.expires > now),
    );
  }

  getForUrl(url: string): Cookie[] {
    const now = Math.floor(Date.now() / 1000);
    const parsed = new URL(url);
    const host = parsed.hostname;
    const path = parsed.pathname;
    const isSecure = parsed.protocol === "https:";

    return this.cookies.filter(
      (c) =>
        domainMatches(c.domain, host) &&
        path.startsWith(c.path) &&
        (!c.secure || isSecure) &&
        (c.expires === 0 || c.expires > now),
    );
  }

  getCookieHeader(url: string): string {
    return this.getForUrl(url)
      .map((c) => `${c.name}=${c.value}`)
      .join("; ");
  }

  removeExpired(): void {
    const now = Math.floor(Date.now() / 1000);
    this.cookies = this.cookies.filter(
      (c) => c.expires === 0 || c.expires > now,
    );
  }

  serialize(): string {
    return serializeNetscapeCookieFile(this.cookies);
  }

  size(): number {
    return this.cookies.length;
  }

  clear(): void {
    this.cookies = [];
  }
}
